Fix runtime issue with opentelemetry
.NoClassDefFoundError: io/opentelemetry/api/incubator/common/ExtendedAttributeKey

 Created spring boot integration test to replicate issue seen in docker environment and then made change to pom to manage clashes on the classpath.